### ISSUE TITLE
Installs on `python3.5`

### ISSUE THREAD

**Issue by StyXman** [dgildeh/JMXQuery#6]
But line 152 has a new 3.6 `f""` string, so it shouldn't. Error:

```
(jmx) mdione@demo-hv2:~/src/works/cloudian/jmx$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jmxquery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mdione/src/works/cloudian/jmx/lib/python3.5/site-packages/jmxquery/__init__.py", line 152
    logger.debug(f"Running command: {command}")
                                             ^
SyntaxError: invalid syntax
```

**Comment by StyXman** [comment]
\o/ Thanks!
